name: 'patrojun6040_dbt_project'

version: '1.0.0'

profile: 'patrojun6040'

config-version: 2

models:
  patrojun6040_analytics:
    materialized: view
    schema: patrojun6040_analytics
    +granularity: monthly

seeds:
  patrojun6040_seeds:
    schema: patrojun6040_analytics

target: dev  # Set your target environment

clean-targets:
  - "patrojun6040_analytics.*"

