postgres-dwh:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 34.89.230.185
      user: patrojun6040
      password: hGXPjHAjO6
      port: 5432
      dbname: d2b_accessment
      schema: patrojun6040_analytics
