S3_CONFIGS:
  BUCKET_NAME: 'd2b-internal-assessment-bucket'
  PREFIX: 'orders_data'
  FILE_LIST:
    - 'shipment_deliveries.csv'
    - "reviews.csv", "orders.csv"
  DOWNLOAD_PATH: '../csv_data'
  S3_REGION: 'eu-central-1'