-- -- Create or replace the table for best performing product
-- {% set schema_name = 'patrojun6040_analytics' %}
--
-- CREATE TABLE IF NOT EXISTS {{ schema_name }}.best_performing_product (
--                                                                          ingestion_date DATE NOT NULL,
--                                                                          product_name VARCHAR NOT NULL,
--                                                                          most_ordered_day DATE NOT NULL,
--                                                                          is_public_holiday BOOLEAN NOT NULL,
--                                                                          tt_review_points INT NOT NULL,
--                                                                          pct_one_star_review FLOAT NOT NULL,
--                                                                          pct_two_star_review FLOAT NOT NULL,
--                                                                          pct_three_star_review FLOAT NOT NULL,
--                                                                          pct_four_star_review FLOAT NOT NULL,
--                                                                          pct_five_star_review FLOAT NOT NULL,
--                                                                          pct_early_shipments FLOAT NOT NULL,
--                                                                          pct_late_shipments FLOAT NOT NULL
-- );
--
-- -- Insert data into the table
-- INSERT INTO {{ schema_name }}.best_performing_product (ingestion_date, product_name, most_ordered_day, is_public_holiday, tt_review_points, pct_one_star_review, pct_two_star_review, pct_three_star_review, pct_four_star_review, pct_five_star_review, pct_early_shipments, pct_late_shipments)
-- SELECT
--     date_trunc('day', current_date) AS ingestion_date,
--     product_name,
--     most_ordered_day,
--     is_public_holiday,
--     tt_review_points,
--     pct_one_star_review,
--     pct_two_star_review,
--     pct_three_star_review,
--     pct_four_star_review,
--     pct_five_star_review,
--     pct_early_shipments,
--     pct_late_shipments
-- FROM
-- -- Your query logic
