S3_CONFIG:
  BUCKET_NAME: 'd2b-internal-assessment-bucket'
  PREFIX: 'orders_data'
  FILE_LIST:
    - "reviews.csv"
    - "orders.csv"
    - 'shipment_deliveries.csv'
  DOWNLOAD_PATH: '../csv_data'
  S3_REGION: 'eu-central-1'
  EXPORT_LOCATION: 'analytics_export/patrojun6040'

WAREHOUSE_CONFIG:
  STAGING_TABLES:
      - "reviews"
      - "orders"
      - 'shipment_deliveries'
  ANALYTICS_TABLES:
     - "agg_public_holiday"
     - "agg_shipments"
     - 'best_performing_product'