name: 'data2bots-DE-challenge'
version: '1.0.0'
config-version: 2
profile: 'postgres-dev'

seed-paths: ["data"]
model-paths: ["models"]
test-paths: ["tests"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  +transient: false # disable transient tables default option
  +copy_grants: true # enable copy previous grants when rebuilding tables and views
  data2botsDE-challenge:
    materialized: table
    marts:
      schema: enrinched_layer
    staging:
      schema: staging_layer

# Configuring seeds (CSV files)
# Full documentation: https://docs.getdbt.com/docs/building-a-dbt-project/seeds
seeds:
  quote_columns: false
  data2bots-DE-challenge:
    orders: # CSV for product orders
      schema: staging_layer
      +column_types:
        order_id: int
        customer_id: int
        order_date: date
        product_id: varchar(32)
        unit_price: int
        quantity: int
        total_price: int
    reviews: # CSV for product reviews
      schema: staging_layer
      +column_types:
        review: int
        product_id: int
    shipment_deliveries: # CSV for product shipments
      schema: staging_layer
      +column_types:
        shipment_id: int
        order_id: int
        shipment_date: date
        delivery_date: date
