version: "3"
services:
  airflow-webserver:
    image: apache/airflow:2.6.2
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-webserver
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/requirements.txt
    command: airflow webserver
    env_file:
      - .env
    depends_on:
      - postgres

  airflow-scheduler:
    image: apache/airflow:2.6.2
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-scheduler
    restart: always
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/requirements.txt
    command: airflow scheduler
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres-airflow
    restart: always
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
